In [26]:
import pandas as pd
import numpy as np
import pymorphy2
import nltk
import stop_words
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC, SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.model_selection import KFold, GridSearchCV, train_test_split, cross_val_score, StratifiedKFold, ParameterGrid
from sklearn import preprocessing
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import MultiLabelBinarizer
from datetime import date
import fastnumbers
import re
from fastnumbers import isfloat, isint
import eli5
from eli5.lime import TextExplainer

In [13]:
data = pd.read_csv('../ucu_sentiment-master/data/train_set.csv', usecols=range(1,11),  parse_dates=['timestamp', 'thread_timestamp'])

In [14]:
data.head()

msg_id    user_id                channel           timestamp  \
0  10648620600  U0KPCJWAC  _call_4_collaboration 2016-05-17 11:30:06   
1  10648631200  U04CH4QBD  _call_4_collaboration 2016-05-17 11:31:52   
2  10648645600  U065VP6F7  _call_4_collaboration 2016-05-17 11:34:16   
3  10648664700  U0KPCJWAC  _call_4_collaboration 2016-05-17 11:37:27   
4  10648667500  U04BFDYPV  _call_4_collaboration 2016-05-17 11:37:55   

                                                text  main_msg    thread_id  \
0  Всем привет! У нас с <@U04BFDYPV> есть идея сд...         1  10648620600   
1  а почему не писать статьи в <http://ods.ai|ods...         1  10648631200   
2                n+1 слишком популярно и без формул?         1  10648645600   
3  <http://opendatascience.ru|opendatascience.ru>...         1  10648664700   
4  <@U065VP6F7>: Принцип примерно такой: у тебя е...         1  10648667500   

     thread_timestamp  replies_count                   reactions  
0 2016-05-17 11:30:06              0  {'count': 6, 'name': '+1'}  
1 2016-05-17 11:31:52              0                          {}  
2 2016-05-17 11:34:16              0                          {}  
3 2016-05-17 11:37:27              0                          {}  
4 2016-05-17 11:37:55              0                          {}

In [15]:
#select top 12 channels
data =data[data.channel.isin(['career', 'big_data', 'deep_learning', 'kaggle_crackers', 
           'lang_python',  'lang_r', 'nlp', 'theory_and_practice', 'welcome', 'bayesian', '_meetings', 'datasets']) 
           & data.main_msg]

In [16]:
# make labels for channels
mappings = {
    'career': 0,
    'theory_and_practice': 1,
    'deep_learning': 2,
    'lang_python': 3,
    '_meetings': 4,
    'kaggle_crackers': 5,
    'big_data': 6,
    'lang_r': 7,
    'nlp': 8,
    'welcome': 9,
    'datasets': 10,
    'bayesian': 11
}

In [17]:
# split on data and data val
date_before = date(2017, 4, 1)
train = data[data['timestamp'] <= date_before]
val = data[data['timestamp'] > date_before]

In [18]:
train_data = train[['channel', 'text']].reset_index()[['channel', 'text']]
train_data['channel'] = train_data.channel.map(mappings)
train_data = train_data.sort_values('channel').reset_index()[['channel', 'text']]

val_data = val[['channel', 'text']].reset_index()[['channel', 'text']]
val_data['channel'] = val_data.channel.map(mappings)
val_data = val_data.sort_values('channel').reset_index()[['channel', 'text']]

train_data.text = train_data.text.astype(str)\
    .apply(lambda x: re.sub('(<\S+>:?)|(\s?:\S+:\s?)|(&gt;)|([\w\.]*@[\w\.]*)', ' ', x)) \
    .apply(lambda x: re.sub('\s+', ' ', x))
train_data = train_data[~train_data.text.apply(lambda x: isfloat(x) or isint(x) or len(x) < 20)]

val_data.text = val_data.text.astype(str)\
    .apply(lambda x: re.sub('(<\S+>:?)|(\s?:\S+:\s?)|(&gt;)|([\w\.]*@[\w\.]*)', ' ', x)) \
    .apply(lambda x: re.sub('\s+', ' ', x))
val_data = val_data[~val_data.text.apply(lambda x: isfloat(x) or isint(x) or len(x) < 20)]

train_text = train_data['text'].astype(str).apply(lambda x: x.lower())
train_labels =  np.asarray(train_data['channel'], dtype='int8')

val_text = val_data['text'].astype(str).apply(lambda x: x.lower())
val_labels = np.asarray(val_data['channel'], dtype='int8')

In [19]:
# without tuning accuracy_score = 50.81%
# accuracy_score = 55.33%
classifier = Pipeline([
    ('vectorizer', TfidfVectorizer(analyzer = 'char', max_features = 1000000, 
                                                       ngram_range = (1, 4))),
    ('clf', OneVsRestClassifier(LogisticRegression(),n_jobs=-1))])

In [20]:
classifier.fit(train_text, train_labels)

Pipeline(steps=[('vectorizer', TfidfVectorizer(analyzer='char', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=1000000, min_df=1,
        ngram_range=(1, 4), norm='l2', preprocessor=None, smooth_idf...None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
          n_jobs=-1))])

In [21]:
predicted = classifier.predict(val_text)

In [22]:
accuracy_score(predicted, val_labels)

0.55334281650071127

In [23]:
categories = ['career',  'theory_and_practice','deep_learning', 'lang_python', '_meetings', 'kaggle_crackers', 'big_data','lang_r',
               'nlp', 'welcome','datasets','bayesian']

In [27]:
te = TextExplainer(random_state=42)
te.fit('запустил спарк выбило такую ошибку', classifier.predict_proba)
te.show_prediction(target_names=list(categories))

In [28]:
classifier.predict(['почему поламался хадуп'])

array([6], dtype=int8)

In [29]:
classifier.predict(val_text)

array([0, 0, 0, ..., 3, 0, 1], dtype=int8)

In [30]:
predicted_val = classifier.decision_function(val_text)

In [31]:
predicted_val.shape

(7733, 12)

In [32]:
softmax = np.exp(predicted_val) / np.sum(np.exp(predicted_val), axis=1)[:, np.newaxis]

In [33]:
np.save('linear_class.npy', softmax)

In [34]:
softmax

array([[ 0.47408063,  0.08195074,  0.02679255, ...,  0.00900392,
         0.00691329,  0.00689136],
       [ 0.90294685,  0.02291404,  0.01832445, ...,  0.00795017,
         0.00506998,  0.00122345],
       [ 0.73641678,  0.06140345,  0.04213868, ...,  0.00574367,
         0.00385626,  0.00282096],
       ..., 
       [ 0.00112408,  0.03524314,  0.04878854, ...,  0.00334064,
         0.00206787,  0.01994189],
       [ 0.4080199 ,  0.03013902,  0.2927247 , ...,  0.0352853 ,
         0.00703018,  0.00693173],
       [ 0.00203772,  0.86526257,  0.02555515, ...,  0.0059855 ,
         0.00435519,  0.02160922]])

In [35]:
len(softmax)

7733

In [36]:
# sun in row = 1 ( prediction)
softmax

array([[ 0.47408063,  0.08195074,  0.02679255, ...,  0.00900392,
         0.00691329,  0.00689136],
       [ 0.90294685,  0.02291404,  0.01832445, ...,  0.00795017,
         0.00506998,  0.00122345],
       [ 0.73641678,  0.06140345,  0.04213868, ...,  0.00574367,
         0.00385626,  0.00282096],
       ..., 
       [ 0.00112408,  0.03524314,  0.04878854, ...,  0.00334064,
         0.00206787,  0.01994189],
       [ 0.4080199 ,  0.03013902,  0.2927247 , ...,  0.0352853 ,
         0.00703018,  0.00693173],
       [ 0.00203772,  0.86526257,  0.02555515, ...,  0.0059855 ,
         0.00435519,  0.02160922]])

In [37]:
classifier.predict(['как у дата санqтиста зарплата в германии'])

array([0], dtype=int8)

In [38]:
classifier.predict(['какие лучшие подходы для сентимент анализа'])

array([1], dtype=int8)

In [39]:
classifier.predict(['почему поламался хадуп'])

array([6], dtype=int8)

In [40]:
classifier.predict(['кто-то принимает участет в соревоаниях'])

array([5], dtype=int8)

In [41]:
# matrix error
pd.crosstab(predicted, val_labels, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted     0    1     2    3    4     5    6    7    8    9   10  11   All
True                                                                         
0          1661  113   190   63   26   596   37   17   53   12   22  11  2801
1            89  515   167  149    6   269   45   28   85    2   29  28  1412
2            67   80   620   75    6   245   23   13   58    4   19  13  1223
3            28  105   100  524    3    73   35   31   24    1    6   3   933
4            61   12    24    9   95    71    5    6    3    3    6   2   297
5            19   18    16    9    0   379    1    4    8    0    5   1   460
6             8    4     0    5    0     6  113    4    0    0    0   1   141
7             1    3     4    6    0     3    1   54    1    0    0   0    73
8             3    4     5    5    0     2    1    1   98    0   13   0   132
9            10    5     5    0    3     1    0    1    4  190    0   0   219
10            0    1     2    1    0     1    0    0    6    0   29   0    40
11            0    1     0    0    0     0    0    0    0    0    0   1     2
All        1947  861  1133  846  139  1646  261  159  340  212  129  60  7733